# Generated by Django 5.2.8 on 2025-11-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon_app', '0003_user_customer_user_employee_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
